backstage/views/analysis.py
from flask import render_template, Blueprint
from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user
from link import *
from api.sql import Analysis

analysis = Blueprint('analysis', __name__, template_folder='../templates')

@analysis.route('/dashboard')
@login_required
def dashboard():
    revenue = []
    dataa = []
    for i in range(1,13):
        row = Analysis.month_price(i)

        if not row:
            revenue.append(0)
        else:
            for j in row:
                revenue.append(j[1])
        
        row = Analysis.month_count(i)
        
        if not row:
            dataa.append(0)
        else:
            for k in row:
                dataa.append(k[1])
        
    row = Analysis.category_sale()
    datab = []
    for i in row:
        temp = {
            'value': i[0],
            'name': i[1]
        }
        datab.append(temp)
    
    row = Analysis.member_sale()
    
    datac = []
    nameList = []
    counter = 0
    
    for i in row:
        counter = counter + 1
        datac.append(i[0])
    for j in row:
        nameList.append(j[2])
    
    counter = counter - 1
    
    row = Analysis.member_sale_count()
    countList = []
    
    for i in row:
        countList.append(i[0])
        
    return render_template('dashboard.html', counter = counter, revenue = revenue, dataa = dataa, datab = datab, datac = datac, nameList = nameList, countList = countList)

backstage/views/manager.py
from flask import Blueprint, render_template, request, url_for, redirect, flash
from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user
from link import *
from api.sql import *
import imp, random, os, string
from werkzeug.utils import secure_filename
from flask import current_app

UPLOAD_FOLDER = 'static/product'
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg'])

manager = Blueprint('manager', __name__, template_folder='../templates')

def config():
    current_app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
    config = current_app.config['UPLOAD_FOLDER'] 
    return config

@manager.route('/', methods=['GET', 'POST'])
@login_required
def home():
    return redirect(url_for('manager.productManager'))

@manager.route('/productManager', methods=['GET', 'POST'])
@login_required
def productManager():
    if request.method == 'GET':
        if(current_user.role == 'user'):
            flash('No permission')
            return redirect(url_for('index'))
        
    if 'delete' in request.values:
        bid = request.values.get('delete')
        # data = Record.delete_check(bid)
        
        # if(data != None):
        #     flash('failed')
        # else:
        # data = Bird.get_product(bid)
        Bird.delete_bird(bid)
    
    elif 'edit' in request.values:
        bid = request.values.get('edit')
        return redirect(url_for('manager.edit', bid=bid))
    
    bird_data = get_all_birds()
    return render_template('productManager.html', bird_data = bird_data, user=current_user.name)

def get_all_birds():
    bird_list = Bird.get_all_product()
    bird_data = []
    for bird in bird_list:
        bird = {
            '鳥類編號': bird[0],
            '鳥類供應商': bird[1],
            '鳥類照護手冊': bird[2],
            '鳥類說明': bird[3],
            '鳥類品種': bird[4],
            '鳥類價格': bird[5]
        }
        bird_data.append(bird)
    return bird_data

@manager.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        data = ""
        while(data != None):
            bId = str(random.randrange( 0, 10000))
            data = Bird.get_product(bId)

        species = request.values.get('species')
        price = request.values.get('price')
        sId = request.values.get('sId')
        gId = request.values.get('gId')
        bDesc = request.values.get('bDesc')
        stock = request.values.get('stock')

        # 檢查是否正確獲取到所有欄位的數據
        if species is None or price is None or sId is None or gId is None or bDesc is None or stock is None:
            flash('所有欄位都是必填的，請確認輸入內容。')
            return redirect(url_for('manager.productManager'))

        # 檢查欄位的長度
        if len(species) < 1 or len(price) < 1:
            flash('商品名稱或價格不可為空。')
            return redirect(url_for('manager.productManager'))


        if (len(species) < 1 or len(price) < 1):
            return redirect(url_for('manager.productManager'))
        
        Bird.add_bird(
            {'bId' : bId,
             'species' : species,
             'sId' : sId,
             'gId' : gId,
             'bDesc' : bDesc,
             'price' : price,
             'stock' : stock,
            }
        )

        return redirect(url_for('manager.productManager'))

    return render_template('productManager.html')

@manager.route('/edit', methods=['GET', 'POST'])
@login_required
def edit():
    if request.method == 'GET':
        if(current_user.role == 'user'):
            flash('No permission')
            return redirect(url_for('bookstore'))

    if request.method == 'POST':
        Bird.update_bird(
            {
            'bid' : request.values.get('bid'),
            'species' : request.values.get('species'),
            'price' : request.values.get('price'),
            'sId' : request.values.get('sId'), 
            'gId' : request.values.get('gId'),
            'bDesc' : request.values.get('bDesc'),
            'stock' : request.values.get('stock'),
            }
        )
        
        return redirect(url_for('manager.productManager'))

    else:
        product = show_info()
        return render_template('edit.html', data=product)


def show_info():
    bid = request.args['bid']
    data = Bird.get_product(bid)
    sId = data[1]
    gId = data[2]
    bDesc = data[3]
    species = data[4]
    price = data[5]
    stock = data[6]

    product = {
        '鳥類編號': bid,
        '供應商編號': sId,
        '照顧手冊編號': gId,
        '鳥類描述': bDesc,
        '鳥類品種': species,
        '鳥類單價': price,
        '鳥類庫存': stock,
    }
    return product


@manager.route('/orderManager', methods=['GET', 'POST'])
@login_required
def orderManager():
    if request.method == 'POST':
        pass
    else:
        order_row = Order.get_order()
        order_data = []
        for i in order_row:
            order = {
                '訂購人編號': i[0],
                '訂購人': i[1],
                '訂單金額': i[2],
                '訂購時間': i[3]
            }
            order_data.append(order)

        return render_template('orderManager.html', order_data=order_data)


# =============Supplier=============

@manager.route('/supplierManager', methods=['GET', 'POST'])
@login_required
def supplierManager():
    if request.method == 'GET':
        if(current_user.role == 'user'):
            flash('No permission')
            return redirect(url_for('index'))
        
    if 'delete' in request.values:
        sid = request.values.get('delete')
        response = Supplier.delete_supplier(sid)
    
    elif 'edit' in request.values:
        sid = request.values.get('edit')
        print(f"================{sid}================")
        return redirect(url_for('manager.editSupplier', sid=sid))
    
    supplier_data = Supplier.get_all_supplier()
    return render_template('supplierManager.html', supplier_data = supplier_data, user=current_user.name)

@manager.route('/addSupplier', methods=['GET', 'POST'])
def addSupplier():
    if request.method == 'POST':
        data = ""
        while(data != None):
            sId = str(random.randrange( 0, 10000))
            data = Supplier.get_supplier(sId)
            sName = request.values.get('sName')
        phone = request.values.get('sPhone')
        rating = request.values.get('sRating')
        # 檢查是否正確獲取到所有欄位的數據
        if sName is None or phone is None or rating is None:
            flash('所有欄位都是必填的，請確認輸入內容。')
            return redirect(url_for('manager.supplierManager'))

        # 檢查欄位的長度
        if len(sName) < 1 or len(phone) < 1:
            flash('供應商名稱與連絡電話不可為空。')
            return redirect(url_for('manager.supplierManager'))

        Supplier.add_supplier(
            {
            'sId' : sId,
            'sName' : sName,
            'phone' : phone,
            'rating' : rating,
            }
        )
        return redirect(url_for('manager.supplierManager'))

    return render_template('supplierManager.html')

@manager.route('/editSupplier', methods=['GET', 'POST'])
@login_required
def editSupplier():
    if request.method == 'GET':
        if(current_user.role == 'user'):
            flash('No permission')
            return redirect(url_for('bookstore'))

    if request.method == 'POST':
        Supplier.update_supplier(
            {
            'sId' : request.values.get('sId'),
            'sName' : request.values.get('sName'),
            'phone' : request.values.get('phone'),
            'rating' : request.values.get('rating'), 
            }
        )
        
        return redirect(url_for('manager.supplierManager'))

    else:
        suppiler = get_supplier()
        return render_template('editSupplier.html', data=suppiler)

def get_supplier():
    sid = request.args['sid']
    data = Supplier.get_supplier(sid)
    sId = data[0]
    sName = data[1]
    sPhone = data[2]
    sRating = data[3]

    supplier = {
        '供應商編號': sId,
        '供應商名稱': sName,
        '連絡電話': sPhone,
        '評分': sRating,
    }
    return supplier

backstage/templates/backstage.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <link rel="icon" href="../static/img/weblogo.ico" type="image/x-icon">
    <script src="../static/offcanvas.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/echarts/5.1.2/echarts.min.js"
        integrity="sha512-ppWbHq6q2f7HAwS481w6qikuC0XEeBnmkRg6KWnWg3zSIbJwWWBgsCDMAxzSB7SVqXzWwSYQ2s8TSJKjnaikMg=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <title> {% block title%}{% endblock title%} </title>
    <link rel="stylesheet" href="../../static/css/navbar.css" />
    {% endblock head %}
</head>

<style>
    main>.container {
        padding: 60px 15px 0;
    }

    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }
</style>

<body class="nav_container">
    <nav class="navbar opacity-75 navbar-expand-lg fixed-top navbar-dark bg-dark nav-links">
        <div class="container-fluid container-xxl">
            <img src="../static/img/weblogo.ico" alt="logo" width="30" height="30">
            <a class="navbar-brand" href="{{ url_for('manager.productManager') }}">&nbsp;寵物店商家管理系統</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="nav collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-links" href="{{ url_for('manager.productManager') }}">商品管理</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-links" href="{{ url_for('manager.orderManager') }}">訂單管理</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-links" href="{{ url_for('manager.supplierManager') }}">供應商管理</a>
                    </li>
                    <li class="nav-item">
                    <li>管理者：{{user}}</li>
                    </li>
                </ul>



                <ul class="navbar-nav me-3 mb-2 mb-lg-0">
                    <li style="color:white;list-style-type:none">管理者：{{user}}</li>
                </ul>

                <a href="{{ url_for('api.logout') }}"><button class="index_btn "
                        style="display: inline-block; min-width: 5em; width: auto;" type="submit">登出</button></a>
            </div>
        </div>
    </nav>
    <br /><br />
    {% block content %}
    {% endblock content %}
</body>

</html>

backstage/templates/editSupplier.html
{% extends "backstage.html" %}
{% block head %}
{{ super() }}

{% endblock head %}

{% block title %}BookStore{% endblock title%}

{% block content%}


<br/>
<div class="container-xl">
  <br/>
  <form method="post" enctype=multipart/form-data action={{ url_for('manager.editSupplier') }}>
    <table class="table table-bordered">
      <tr>
        <th>供應商編號</th>
        <td><input class="form-control" type="text" value="{{ data.供應商編號 }}" name="sId" readonly required class="id_input"></td>
      </tr>
      <tr>
        <th>供應商名稱</th>
        <td><input class="form-control" type="text" value="{{ data.供應商名稱 }}" name="sName" required class="id_input"></td>
      </tr>
      <tr>
        <th>連絡電話</th>
        <td><input class="form-control" type="text" value="{{ data.連絡電話 }}" name="phone" required></td>
      </tr>
      <tr>
        <th>評分</th>
        <td><input class="form-control" type="text" value="{{ data.評分 }}" name="rating" required></td>
      </tr>
    </table>
    <center>
      <div class="option">
        <button class="btn btn-outline-success" type="submit">確定修改</button> 
        <a href="{{ url_for('manager.supplierManager') }}"><button class="btn btn-outline-danger">回供應商管理</button></a>
      </div>
    </center>

  </form>
</div>



{% endblock content%}

backstage/templates/manager.html
{% extends "backstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}BookStore{% endblock title%}

{% block content%}
<div class="btn_div">
  <h1 class="book_title left">31 Lab Book Store</h1>
  <a href="{{ url_for('analysis.dashboard') }}" title="資料分析"><img class="cart"
      src="{{ url_for('static', filename='./img/dashboard.png') }}"></a>
  <a href="{{ url_for('logout') }}" title="登出"><img class="logout"
      src="{{ url_for('static', filename='./img/logout.png') }}"></a>
</div>
<div class="btn_div">
  <p class="welcome">歡迎 , 管理者：{{user}}</p>
</div>
{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}

<script language="javascript">

  alert('您沒有使用者的權限喔！');

</script>

{% endif %}
{% endwith %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'faild' %}

<script language="javascript">

  alert('有使用者有使用到這筆資料，所以不能刪除');

</script>

{% endif %}
{% endwith %}

<div class="book_table">
  <form method='post' action={{ url_for('manager') }}>
    <table cellpadding="10" border='3'>
      <tr>
        <th>商品編號</th>
        <th>商品名稱</th>
        <th>商品售價</th>
        <th>商品類別</th>
        <th></th>
        <th></th>
      </tr>
      {% for book in book_data %}
      <tr>
        <td> {{ book.商品編號 }}</td>
        <td> {{ book.商品名稱 }}</td>
        <td> {{ book.商品售價 }}</td>
        <td> {{ book.商品類別 }}</td>
        <td>
          <button type="submit" value="{{book.商品編號}}" name="edit">修改
          </button>
        </td>
        <td>
          <button type="submit" value="{{book.商品編號}}" name="delete"
            onclick="return (confirm('你確定要刪除 \'{{ book.商品名稱 }}\' 嗎？'))">
            刪除
          </button>
        </td>
      </tr>
      {% endfor %}
    </table>
    <div class="book_table">
      <a href={{ url_for('add')}}><button value="new" name="new" type="button"> 上架新商品</button></a>
    </div>
  </form>

</div>

{% endblock content%}

backstage/templates/productManager.html
{% extends "backstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %} 鳥類管理 {% endblock title %}

{% block content %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}
<script language="javascript">
    alert('您沒有使用者的權限喔！');
</script>
{% endif %}
{% endwith %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'failed' %}
<script language="javascript">
    alert('有使用者有使用到這筆資料，所以不能刪除');
</script>
{% endif %}
{% endwith %}

<script>
    $(document).ready(function () {
        $("#keyword").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#product tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>
<style>
    html,
    body {
        height: auto;
        overflow: auto;
        background-color: #ecf0f1;
    }

    table th,
    table td {
        text-align: center;
        vertical-align: middle;
    }

    .btn-danger {
        background-color: #ac2424;
        border-color: #ac2424;
        color: #fff;
    }

    .btn-danger:hover {
        background-color: #6d2525;
        border-color: #6d2525;
    }

    .btn-success {
        background-color: #285a5e;
        border-color: #285a5e;
        color: #fff;
    }

    .btn-success:hover {
        background-color: #1b4447;
        border-color: #1b4447;
    }
</style>
&nbsp;
&nbsp;
<div class="d-flex justify-content-between container-xxl">
    <div class="d-flex col-sm-4">
        <span class="input-group-text" id="basic-addon1">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search"
                viewBox="0 0 16 16">
                <path
                    d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
            </svg>
        </span>
        <input class="form-control me-2" id="keyword" placeholder="搜尋鳥類" aria-label="Search">
    </div>
    <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
        新增鳥類
    </button>
</div>

<form method="post" enctype=multipart/form-data action={{ url_for('manager.add') }}>
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
        aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">新增鳥類</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="inputBirdSpecies" class="form-label">鳥類品種</label>
                        <input type="text" class="form-control" id="inputBirdSpecies" name="species" required>
                    </div>
                    <div class="mb-3">
                        <label for="inputUnitPrice" class="form-label">鳥類單價</label>
                        <input type="number" class="form-control" id="inputUnitPrice" name="price" required>
                    </div>
                    <div class="mb-3">
                        <label for="inputSupplierId" class="form-label">供應商id</label>
                        <input type="number" class="form-control" id="inputSupplierId" name="sId" required>
                    </div>
                    <div class="mb-3">
                        <label for="inputGuideId" class="form-label">照護手冊id</label>
                        <input type="number" class="form-control" id="inputGuideId" name="gId" required>
                    </div>
                    <div class="mb-3">
                        <label for="inputProductDesc" class="form-label">鳥類說明</label>
                        <textarea class="form-control" id="inputProductDesc" name="bDesc" required></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="inputStock" class="form-label">鳥類庫存</label>
                        <input type="number" class="form-control" id="inputStock" name="stock" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">取消</button>
                    <button type="submit" class="btn btn-success">確定新增</button>
                </div>
            </div>
        </div>
    </div>
</form>

<br />

<div class="container-xxl">
    <form method='post' action={{ url_for('manager.productManager') }}>
        <table id="manager" class="table table-bordered">
            <thead>
                <tr>
                    <th width="10%">
                        <center>鳥類編號</center>
                    </th>
                    <th width="20%">
                        <center>鳥類品種</center>
                    </th>
                    <th width="15%">
                        <center>鳥類價格</center>
                    </th>
                    <th width="15%">
                        <center>鳥類庫存</center>
                    </th>
                    <th colspan="2">
                        <center>資料操作</center>
                    </th>
                </tr>
            </thead>
            <tbody id="product">
                {% for bird in bird_data %}
                <tr>
                    <td>
                        <center>{{ bird.鳥類編號 }}</center>
                    </td>
                    <td>
                        <center>{{ bird.鳥類品種 }}</center>
                    </td>
                    <td>
                        <center>{{ bird.鳥類價格 }}</center>
                    </td>
                    <td>
                        <center>{{ bird.鳥類庫存 }}</center>
                    </td>
                    <td>
                        <center><button type="submit" value="{{bird.鳥類編號}}" name="edit"
                                class="btn btn-success">編輯鳥類</button></center>
                    </td>
                    <td>
                        <center><button type="submit" value="{{bird.鳥類編號}}" name="delete"
                                onclick="return (confirm('你確定要刪除 \'{{ bird.鳥類品種 }}\' 嗎？'))"
                                class="btn btn-danger">刪除鳥類</button></center>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </form>
</div>

<script>
    function have_product() {
        alert('有使用者有使用到這筆資料，所以不能刪除');
    }
</script>

{% endblock content %}

backstage/templates/supplierManager.html
{% extends "backstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %} 供應商管理 {% endblock title %}

{% block content %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}

<script language="javascript">

    alert('您沒有使用者的權限喔！');

</script>


{% endif %}
{% endwith %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'failed' %}

<script language="javascript">

    alert('有使用者有使用到這筆資料，所以不能刪除');

</script>

{% endif %}
{% endwith %}

<script>
    $(document).ready(function () {
        $("#keyword").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#product tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>
<style>
    html,
    body {
        height: auto;
        overflow: auto;
        background-color: #ecf0f1;
    }

    table th,
    table td {
        text-align: center;
        vertical-align: middle;
    }

    .btn-danger {
        background-color: #ac2424;
        border-color: #ac2424;
        color: #fff;
    }

    .btn-danger:hover {
        background-color: #6d2525;
        border-color: #6d2525;
    }

    .btn-success {
        background-color: #285a5e;
        border-color: #285a5e;
        color: #fff;
    }

    .btn-success:hover {
        background-color: #1b4447;
        border-color: #1b4447;
    }
</style>
&nbsp;
&nbsp;
<div class="d-flex justify-content-between container-xxl">
    <div class="d-flex col-sm-4">
        <span class="input-group-text" id="basic-addon1">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search"
                viewBox="0 0 16 16">
                <path
                    d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
            </svg>
        </span>
        <input class="form-control me-2" id="keyword" placeholder="搜尋商品" aria-label="Search">
    </div>
    <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
        新增供應商
    </button>
</div>

<!-- 新增供應商的form -->
<form method="post" enctype=multipart/form-data action={{ url_for('manager.addSupplier') }}>
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
        aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">新增供應商</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="inputSupplierName" class="form-label">供應商名稱</label>
                        <input type="text" class="form-control" id="inputSupplierName" name="sName" required>
                    </div>
                    <div class="mb-3">
                        <label for="inputPhone" class="form-label">連絡電話</label>
                        <input type="number" class="form-control" id="inputPhone" name="sPhone" required>
                    </div>
                    <div class="mb-3">
                        <label for="inputSupplierRate" class="form-label">供應商評分</label>
                        <input type="number" class="form-control" id="inputSupplierRate" name="sRating" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">取消</button>
                    <button type="submit" class="btn btn-success">確定新增</button>
                </div>
            </div>
        </div>
    </div>
</form>

<br />

<div class="container-xxl">

    <form method='post' action={{ url_for('manager.supplierManager') }}>
        <table id="manager" class="table table-bordered">
            <thead>
                <tr>
                    <th width="10%">
                        <center>供應商編號</center>
                    </th>
                    <th width="20%">
                        <center>供應商名稱</center>
                    </th>
                    <th width="15%">
                        <center>連絡電話</center>
                    </th>
                    <th width="15%">
                        <center>供應商評分</center>
                    </th>
                </tr>
            </thead>
            <tbody id="product">
                {% for supplier in supplier_data %}
                <tr>
                    <td>
                        <center>{{ supplier[0] }}</center>
                    </td>
                    <td>
                        <center>{{ supplier[1] }}</center>
                    </td>
                    <td>
                        <center>{{ supplier[2] }}</center>
                    </td>
                    <td>
                        <center>{{ supplier[3] }}</center>
                    </td>
                    <td>
                        <center><button type="submit" value="{{supplier[0]}}" name="edit"
                                class="btn btn-success">編輯供應商</button></center>
                    </td>
                    <td>
                        <center><button type="submit" value="{{supplier[0]}}" name="delete"
                                onclick="return (confirm('你確定要刪除 \'{{ supplier[1] }}\' 嗎？'))"
                                class="btn btn-danger">刪除供應商</button></center>
                    </td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
    </form>
</div>

<script>
    function have_product() {
        alert('有使用者有使用到這筆資料，所以不能刪除');
    }
</script>

{% endblock content %}